[package]
name = "rain_collected"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
libc = "0.2.101"

[dev-dependencies]
criterion = "0.5.1"

[build-dependencies]
cmake = "0.1.48"

[[bench]]
name = "compute_rain_collected_trap"
harness = false
